/**
 * GET /api/sso/circle?token=<jwt>
 *
 * Entry point for Circle → Portal SSO. The user arrives here from
 * cco.academy with a short-lived HS256 JWT in the `token` query param,
 * generated by the token-signing service described in
 * docs/CIRCLE_SSO_SETUP.md. We verify the JWT (signature + exp + max
 * age + required claims), upsert the user in Podio + Neon, set the
 * cco_session cookie, and redirect to /catalog.
 *
 * Error handling:
 *   - Missing token            → 400
 *   - Invalid/expired JWT      → 302 to /sign-in?sso_error=invalid_token
 *   - Any upstream failure     → 302 to /sign-in?sso_error=server_error
 *
 * We don't surface the specific verification failure to the browser
 * (don't tell attackers why their forged token was rejected).
 */

import type { NextRequest } from "next/server";
import { createSession } from "@/lib/auth";
import { upsertCircleUser, verifyCircleAuthJwt } from "@/lib/sso";

export const runtime = "nodejs";

export async function GET(request: NextRequest): Promise<Response> {
  const token = request.nextUrl.searchParams.get("token");
  if (!token) {
    return new Response("missing token", { status: 400 });
  }

  let identity;
  try {
    identity = await verifyCircleAuthJwt(token);
  } catch (err) {
    // Log server-side so we can diagnose if a legitimate user hits
    // this, but keep the response intentionally vague.
    console.warn(
      "[sso/circle] JWT verification failed:",
      err instanceof Error ? err.message : err
    );
    return redirect(request, "/sign-in?sso_error=invalid_token");
  }

  let upserted;
  try {
    upserted = await upsertCircleUser({
      email: identity.email,
      fullName: identity.fullName,
      circleMember: identity.circleMember,
    });
  } catch (err) {
    console.error("[sso/circle] upsert failed:", err);
    return redirect(request, "/sign-in?sso_error=server_error");
  }

  try {
    // Sets the cco_session cookie on the outgoing response. Next.js
    // attaches cookies set via cookies().set() from createSession() to
    // whatever response we return below.
    await createSession(upserted.contactId);
  } catch (err) {
    console.error("[sso/circle] session creation failed:", err);
    return redirect(request, "/sign-in?sso_error=server_error");
  }

  return redirect(request, "/catalog");
}

function redirect(request: NextRequest, path: string): Response {
  const target = new URL(path, request.nextUrl);
  return new Response(null, {
    status: 302,
    headers: { Location: target.toString() },
  });
}
