#!/usr/bin/env python3
"""
CCO-T031: Stand up the "Password Resets" Podio app in the CCO-Portal space.

The portal will create one item per forgot-password request. A Podio workflow
(Globiflow or native) listens for item-create and emails the recipient using
recipient_email + reset_url. Status flips to Sent / Skipped / Failed.

If recipient_profile_ref is blank (i.e. the email didn't match a Profile),
the workflow should mark status=Skipped and NOT send — this preserves the
enumeration-safe behaviour of the /forgot-password endpoint.

App location: CCO-Portal space (10191082), same space as CCO Platform Profiles
(30640719), so the recipient_profile_ref is an intra-space reference.

Uses jakub-fs Podio profile.

Idempotent: re-running checks for an existing "Password Resets" app by name
and short-circuits if found; if found, also checks each field by external_id
and adds any that are missing.

References:
  - Podio category fields PUT: settings at TOP LEVEL (postmortem 2026-04-09).
    For CREATE (this script's path), settings live nested in config per
    Podio's create-field spec.
  - SESSION.md / tasks.md CCO-T031 for the field schema rationale.
"""
import json
import os
import sys
from datetime import datetime
from pathlib import Path

SKILL_SCRIPTS = Path(r"C:\Users\jakub\.codex\skills\podio-build-kit\scripts")
sys.path.insert(0, str(SKILL_SCRIPTS))

os.environ.setdefault("PODIO_PROFILE", "jakub-fs")

from _spec_lib import load_token, api_get, api_post, sleep  # noqa: E402

CCO_PORTAL_SPACE_ID = 10191082
PROFILES_APP_ID = 30640719  # CCO Platform Profiles (legacy credential store; not the live auth target)
CONTACTS_APP_ID = 14660191  # Canonical credential record per auth.ts (cross-space ref into -CCO Main Hub)
APP_NAME = "Password Resets"
ITEM_NAME = "Password Reset"

APP_DESCRIPTION = (
    "Single-use password reset emails dispatched by the CCO portal (CCO-T031). "
    "Item-create triggers the Podio workflow that emails recipient_email with "
    "reset_url. Portal sets status=Pending; workflow updates to Sent / "
    "Skipped / Failed. If recipient_profile_ref is blank (unknown email), the "
    "workflow MUST mark status=Skipped and NOT send — this preserves the "
    "enumeration-safe behaviour of the /forgot-password endpoint."
)

# Field specs in display order. Each is (type, external_id, config_dict).
FIELDS: list[tuple[str, str, dict]] = [
    (
        "email",
        "recipient-email",
        {
            "label": "Recipient Email",
            "description": "The address to send the reset email to.",
            "required": True,
            "settings": {},
        },
    ),
    (
        # Original create used external_id "recipient-profile-ref"; Podio strips
        # trailing "-ref" on app-reference fields, so the real external_id is
        # "recipient-profile". Jakub later renamed the label to "Recipient
        # Contact" and repointed the reference at Contacts (14660191) — the
        # canonical credential record in the live auth code (auth.ts). Spec
        # below matches the post-rename state so re-runs are true no-ops.
        "app",
        "recipient-profile",
        {
            "label": "Recipient Contact",
            "description": (
                "Link to the Contact (app 14660191) whose password is being "
                "reset. Contacts is the canonical credential record per "
                "auth.ts. Blank when the email didn't match any Contact — "
                "workflow then sets status=Skipped without sending "
                "(enumeration-safe)."
            ),
            "required": False,
            "settings": {
                "referenceable_types": [CONTACTS_APP_ID],
                "multiple": False,
            },
        },
    ),
    (
        "text",
        "reset-url",
        {
            "label": "Reset URL",
            "description": (
                "Full URL to land on, with the signed reset token in the "
                "querystring. Generated by the portal; opaque to Mary."
            ),
            "required": True,
            "settings": {
                "size": "large",
                "format": "plain",
            },
        },
    ),
    (
        "date",
        "expires-at",
        {
            "label": "Expires At",
            "description": (
                "Copy of the JWT exp claim. Workflow may skip sending if the "
                "current time is past this (e.g. a long Podio backlog)."
            ),
            "required": True,
            "settings": {
                "end": "disabled",
                "time": "enabled",
                "calendar": False,
            },
        },
    ),
    (
        "category",
        "status",
        {
            "label": "Status",
            "description": (
                "Workflow state. Portal creates as Pending; workflow updates "
                "after attempting the send."
            ),
            "required": True,
            "settings": {
                "multiple": False,
                "display": "inline",
                "options": [
                    {"text": "Pending", "color": "FFF6C9"},  # yellow
                    {"text": "Sent",    "color": "DCEBD8"},  # green
                    {"text": "Skipped", "color": "E8E8E8"},  # gray
                    {"text": "Failed",  "color": "FBC0BC"},  # red/pink
                ],
            },
        },
    ),
    (
        "date",
        "used-at",
        {
            "label": "Used At",
            "description": (
                "Set by the portal when the reset token is successfully "
                "consumed. Informational only — single-use enforcement lives "
                "on the Profile, not here."
            ),
            "required": False,
            "settings": {
                "end": "disabled",
                "time": "enabled",
                "calendar": False,
            },
        },
    ),
]


def find_existing_app(access: str) -> int | None:
    apps = api_get(f"/app/space/{CCO_PORTAL_SPACE_ID}", access)
    for a in apps:
        if a.get("config", {}).get("name") == APP_NAME:
            return a.get("app_id")
    return None


def existing_field_external_ids(access: str, app_id: int) -> set[str]:
    app = api_get(f"/app/{app_id}", access)
    return {
        f.get("external_id")
        for f in app.get("fields", [])
        if f.get("status") == "active" and f.get("external_id")
    }


def create_app(access: str) -> int:
    # icon_id 275 is what "Master Portal Profiles" uses in this same space —
    # visually groups Password Resets next to the credentials-area apps.
    icon_id = 275
    payload = {
        "space_id": CCO_PORTAL_SPACE_ID,
        "config": {
            "name": APP_NAME,
            "item_name": ITEM_NAME,
            "description": APP_DESCRIPTION,
            "type": "standard",
            "usage": (
                "Created by portal; consumed by Podio workflow that sends the "
                "reset email."
            ),
            "external_id": "password-resets",
            "icon_id": icon_id,
            "icon": f"{icon_id}.png",
        },
    }
    print(f"POST /app/  (creating {APP_NAME!r} in space {CCO_PORTAL_SPACE_ID})")
    resp = api_post("/app/", access, payload)
    app_id = resp.get("app_id")
    if not app_id:
        raise SystemExit(f"App-create returned no app_id: {resp!r}")
    print(f"  app_id = {app_id}")
    return app_id


def add_field(access: str, app_id: int, ftype: str, external_id: str, cfg: dict) -> dict:
    payload = {
        "type": ftype,
        "external_id": external_id,
        "config": cfg,
    }
    print(f"  POST /app/{app_id}/field/  type={ftype} external_id={external_id}")
    return api_post(f"/app/{app_id}/field/", access, payload)


def snapshot(access: str, app_id: int) -> dict:
    app = api_get(f"/app/{app_id}", access)
    fields = []
    for f in app.get("fields", []):
        cfg = f.get("config", {})
        opts = (cfg.get("settings") or {}).get("options") or []
        fields.append({
            "field_id": f.get("field_id"),
            "external_id": f.get("external_id"),
            "type": f.get("type"),
            "label": cfg.get("label"),
            "status": f.get("status"),
            "settings": cfg.get("settings"),
            "options": [
                {"id": o.get("id"), "text": o.get("text"), "status": o.get("status")}
                for o in opts
            ] if opts else None,
        })
    return {
        "captured_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "captured_by": "podio-create-password-resets-app.py (jakub-fs)",
        "app_id": app_id,
        "space_id": app.get("space_id"),
        "name": app.get("config", {}).get("name"),
        "item_name": app.get("config", {}).get("item_name"),
        "description": app.get("config", {}).get("description"),
        "fields": fields,
    }


def main() -> int:
    access = load_token()
    print(f"Using PODIO_PROFILE={os.environ.get('PODIO_PROFILE')}")
    print()

    existing = find_existing_app(access)
    if existing:
        print(f"App {APP_NAME!r} already exists: app_id={existing}. Will reconcile fields.")
        app_id = existing
    else:
        app_id = create_app(access)
        sleep()

    have = existing_field_external_ids(access, app_id)
    print(f"existing active fields: {sorted(have)}")

    for ftype, external_id, cfg in FIELDS:
        if external_id in have:
            print(f"  skip (already present): {external_id}")
            continue
        add_field(access, app_id, ftype, external_id, cfg)
        sleep()

    print()
    snap = snapshot(access, app_id)

    snap_dir = Path(__file__).resolve().parent.parent / "snapshots"
    snap_dir.mkdir(exist_ok=True)
    snap_path = snap_dir / "password-resets-app.json"
    snap_path.write_text(json.dumps(snap, indent=2))
    print(f"snapshot -> {snap_path}")
    print()
    print(f"app_id = {snap['app_id']}")
    print(f"space_id = {snap['space_id']}")
    print("fields:")
    for f in snap["fields"]:
        if f["status"] != "active":
            continue
        print(f"  - field_id={f['field_id']}  external_id={f['external_id']}  type={f['type']}  label={f['label']!r}")
        if f["options"]:
            for o in f["options"]:
                print(f"      option id={o['id']} text={o['text']!r} status={o['status']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
